spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: xibb5714
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
server:
  port: 8081
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl